### ISSUE TITLE
How to run qlora with BPT?

### ISSUE THREAD

**Issue by tiendung** [arnavdantuluri/long-context-transformers#1]
For now I see qlora using FlashAttentionWrapper, then I replace Flash... with BPT... then I got some errors

Can you help to provide a file with BPT by default?

**Comment by arnavdantuluri** [comment]
thanks for the issue, I added a file for running BPT + QLoRa and fixed an issue with Flash Attention. However in it's current state I would not recommend using the BPT implementation since a for loop in python incurs way too many overheads around inner kernels. Compilers like JAX don’t have visibility over pure python for loop, they have optimizations such as jax.lax.scan that are unfortunately not available in pytorch. I am working with some folks to get an optimized implementation, it would be better to use BPT then. Until then I would suggest using Flash attn + QLoRa unless your task requires 16k/32k+ context windows
